collections:
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
    values:
      layout: "default"